version: '3.8'

services:
  server:
    build: ./server
    container_name: computer-shop-server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - CONNECT_DB=mongodb://mongo:27017/computer-shop
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: >
      sh -c "npm start"

  client:
    build: ./client
    container_name: computer-shop-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:3000

  mongo:
    image: mongo:latest
    container_name: computer-shop-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  mongo-setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    container_name: computer-shop-mongo-setup
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/computer-shop
    command: sh -c "node setup-database.js"

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
